const movie = {
  actors: "Hanna Hall, Lane Compton, Michael Kaiser",
  writer: "Ken Maskrey, Bill Mays, Laurie Pokin",
  year: "2008",
  imdbRating: "4.2",
  country: "United States",
  director: "Brian McCulley",
  genre: "Horror, Thriller",
  runtime: "85 min",
  title: "Text",
  plot: "Four friends search for the answers to a series of deadly text messages killing students at their high school.",
  poster:
    "https://m.media-amazon.com/images/M/MV5BMTQyNzkyMjQxM15BMl5BanBnXkFtZTgwNTUyNTMxMjE@._V1_SX300.jpg",
  released: "01 Sep 2008",

  Production: "N/A",
  Rated: "Not Rated",
  Ratings: "",
  Response: "True",
  Type: "movie",
  Website: "N/A",
  imdbID: "tt1190078",
  imdbVotes: "108",
  awards: "N/A",
  BoxOffice: "N/A",
  DVD: "22 May 2017",
  Language: "English",
  metascore: "N/A",
};
